#' Summary for `cd_ratios_summary` Object
#'
#' Provides a concise summary for a `cd_ratios_summary` object, which includes
#' the calculated indicator ratios across specified pairs (e.g., ANC1/Penta1,
#' Penta1/Penta3, OPV1/OPV3) by year. This summary facilitates understanding of
#' inter-indicator consistency over time.
#'
#' @param x A `cd_ratios_summary` object, typically generated by the
#'   `calculate_ratios_summary` function. It contains year-wise ratios for
#'   specified indicator pairs.
#' @param ... Additional arguments to support S3 method compatibility.
#'
#' @return A character vector providing a descriptive title that clarifies the
#'   type of summary and the indicator ratios reported, to enhance interpretation
#'   when viewing the data.
#'
#' @export
tbl_sum.cd_ratios_summary <- function(x, ...) {
  c(
    'Table 3a.b' = 'Ratios of ANC1/Penta1, Penta1/Penta3, and OPV1/OPV3 by Year',
    NextMethod()
  )
}

#' Summary for `cd_district_ratios_summary` Object
#'
#' Provides a customized summary for a `cd_district_ratios_summary` object, which
#' includes the percentage of districts meeting the adequacy criteria (e.g., ratios
#' within the range of 1.0 to 1.5) across specified indicator pairs by year. This
#' summary aids in monitoring health indicator alignment at a district level over time.
#'
#' @param x A `cd_district_ratios_summary` object, typically created by the
#'   `calculate_district_ratios_summary` function, containing adequacy checks for
#'   district-level indicator ratios by year.
#' @param ... Additional arguments to support S3 method compatibility.
#'
#' @return A character vector providing a descriptive title indicating the percentage
#'   of districts with indicator ratios that meet adequacy criteria, aiding in data
#'   quality interpretation.
#'
#' @export
tbl_sum.cd_district_ratios_summary <- function(x, ...) {
  c(
    'Table 3c.d' = 'Percentage of Districts with Adequate Ratios (between 1.0 and 1.5)',
    NextMethod()
  )
}
