#' Table Summary for National Coverage Estimates
#'
#' `tbl_sum.cd_indicator_coverage` generates a summary label for national coverage estimates tables,
#' providing a clear indication of the data contents. This function is designed to be used as a custom
#' summary method for objects of class `cd_indicator_coverage`, creating a consistent table title for
#' outputs.
#'
#' @param x An object of class `cd_indicator_coverage`, typically a data frame or tibble containing
#'   national coverage estimates for various health indicators.
#' @param ... Additional arguments passed to `NextMethod()` for extending or customizing the summary
#'   method.
#'
#' @return A named character vector where the first element, `"Table"`, is titled `"National Coverage Estimates"`,
#'   followed by the summary generated by the next method in the class hierarchy.
#'
#' @details
#' This function is part of the summary method hierarchy for `cd_indicator_coverage` objects.
#' By adding a specific table title (`"National Coverage Estimates"`), this function helps standardize
#' output tables, ensuring consistency in reports and summaries for national health coverage indicators.
#'
#' @examples
#' \dontrun{
#'   # Assuming `data` is of class `cd_indicator_coverage`
#'   tbl_sum.cd_indicator_coverage(data)
#' }
#'
#' @export
tbl_sum.cd_indicator_coverage <- function(x, ...) {
  c(
    'Table' = 'National Coverage Estimates',
    NextMethod()
  )
}

